### ISSUE TITLE
The GUI is not importing information from linux-cli.

### ISSUE THREAD

**Issue by Chummpp** [calexandru2018/linux-gui-legacy#75]
**Describe the bug**
After typing sudo protonvpn-gui the terminal came back with what you see bellow.
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn-gui", line 11, in <module>
    load_entry_point('protonvpn-gui==2.0.7', 'console_scripts', 'protonvpn-gui')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_linux_gui/gui.py", line 16, in <module>
    from .utils import (
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_linux_gui/utils.py", line 12, in <module>
    from protonvpn_cli.utils import (
ImportError: cannot import name 'make_ovpn_template'

**To Reproduce**
1. Type sudo protonvpn-gui
2. See error

**Expected behavior**
I expected the GUI to load.

**Screenshots**
https://postimg.cc/8jVhCVJC, https://i.postimg.cc/xTXgtf9L/fdhgfhjgfj.png

**Desktop (please complete the following information):**
 - OS: [Linux mint 19.3]

**Comment by calexandru2018** [comment]
Hi again @Chummpp :)

This has already been reported in #72 , please do take a look into that one.
I will be closing it since it is a duplicate.
