### ISSUE TITLE
Fails to start > ImportError: cannot import name 'make_ovpn_template' from 'protonvpn_cli.utils'

### ISSUE THREAD

**Issue by SCCOBN** [calexandru2018/linux-gui-legacy#82]
**Describe the bug**
Typing protonvpn-gui in terminal outputs this
`Traceback (most recent call last):
  File "/usr/bin/protonvpn-gui", line 11, in <module>
    load_entry_point('protonvpn-linux-gui-calexandru2018==2.0.7', 'console_scripts', 'protonvpn-gui')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/protonvpn_linux_gui/gui.py", line 16, in <module>
    from .utils import (
  File "/usr/lib/python3.8/site-packages/protonvpn_linux_gui/utils.py", line 12, in <module>
    from protonvpn_cli.utils import (
ImportError: cannot import name 'make_ovpn_template' from 'protonvpn_cli.utils' (/usr/lib/python3.8/site-packages/protonvpn_cli/utils.py)`

You had an issue earlier this week, I read it, I was waiting for update and it came, my version of the program is 2.0.7-3 protonvpn-cli-ng 2.2.4.1
OS, Arch Linux

**Comment by musikerv** [comment]
`user@thinklinux:~$ sudo protonvpn-gui
[sudo] password for user: 
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn-gui", line 11, in <module>
    load_entry_point('protonvpn-gui==2.0.7', 'console_scripts', 'protonvpn-gui')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_linux_gui/gui.py", line 16, in <module>
    from .utils import (
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_linux_gui/utils.py", line 12, in <module>
    from protonvpn_cli.utils import (
ImportError: cannot import name 'make_ovpn_template'
`
Same error on Ubuntu 18.04.4 LTS, Gnome 3.28.4, pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6), Python 2.7.17, Python 3.6.9

**Comment by calexandru2018** [comment]
#83
