### ISSUE TITLE
Empty dialog box on connection attempt

### ISSUE THREAD

**Issue by ghost** [calexandru2018/linux-gui-legacy#87]
**Describe the bug**
The connection doesnt work and i dont get any error message.

**To Reproduce**
1. Go to GUI
2. Attempt to connect
3. Empty dialog box pops up and connection fails

**Expected behavior**
Should connect correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/42862719/85201324-77cf6180-b2f6-11ea-92ca-dcedd4291152.png)

version: 
2.0.7

with cli at 2.2.2

**Comment by calexandru2018** [comment]
Hi @dioio-io :)

Appreciate that you took your time in creating this issue. I though have a couple of questions:
1. Which button do you press to connect ?
2. Does this happen with all sorts of buttons (profiles -> fastest; Quick Connect; Country/Server) ?
3. Was this your fist time connecting to the VPN via the app ?

**Comment by ghost** [comment]
Hello @calexandru2018 

> Which button do you press to connect ?
> Does this happen with all sorts of buttons (profiles -> fastest; Quick Connect; Country/Server) ?

Yes, it happens with Quick Connect, it happens when i try to connect to a specific server as well.
> Was this your fist time connecting to the VPN via the app ?

yes

**Comment by calexandru2018** [comment]
Could you post the gui log results ?

**Comment by ghost** [comment]
How can access said log?
If I run the gui from the terminal nothing shows up on the terminal

**Comment by calexandru2018** [comment]
The GUI logs are located under /home/[your_username]/.pvpn-gui/

Edit: What distro&version are you on ?

**Comment by bnctth** [comment]
Hey there!
The same is for me. I use ubuntu 20.04, ProtonVPN-CLI v2.2.2, ProtonVPNGUI v.2.0.7, it happens on every button. My log file:
```
2020-07-03 13:54:09,378 — protonvpn-linux-gui — DEBUG — initialize_gui:787 —
______________________________________

        INITIALIZING NEW GUI WINDOW
______________________________________

2020-07-03 13:54:09,385 — protonvpn-linux-gui — DEBUG — get_gui_processes:1023 — >>> Running "get_gui_processes".
2020-07-03 13:54:09,437 — protonvpn-linux-gui — DEBUG — get_gui_processes:1029 — >>> Existing process running: ['4156']
2020-07-03 13:54:09,438 — protonvpn-linux-gui — DEBUG — initialize_gui:823 — >>> Loading DashboardWindow
2020-07-03 13:54:09,452 — protonvpn-linux-gui — DEBUG — load_content_on_start:53 — >>> Running "load_on_start".
2020-07-03 13:54:11,457 — protonvpn-linux-gui — DEBUG — load_on_start:331 — >>> Running "load_on_start". Params: {'interface': <Gtk.Builder object at 0x7f809cd575c0 (GtkBuilder at 0x27a3d00)>, 'messagedialog_la>
2020-07-03 13:54:11,458 — protonvpn-linux-gui — DEBUG — custom_get_ip_info:1008 — Getting IP Information
2020-07-03 13:54:11,458 — protonvpn-linux-gui — DEBUG — custom_call_api:238 — Initiating custom API Call: https://api.protonvpn.ch/vpn/location
2020-07-03 13:54:11,718 — protonvpn-linux-gui — DEBUG — update_labels_server_list:360 — >>> Running "update_labels_server_list" getting servers.
2020-07-03 13:54:11,741 — protonvpn-linux-gui — DEBUG — update_labels_status:387 — >>> Running "update_labels_status" getting servers, is_connected and connected_server.
2020-07-03 13:54:11,745 — protonvpn-linux-gui — DEBUG — load_content_on_start:73 — >>> Ended tasks in "load_on_start" thread.
2020-07-03 13:54:15,005 — protonvpn-linux-gui — DEBUG — main_conn_disc_button_label:358 — >>> Starting "main_conn_disc_button_label" thread.
2020-07-03 13:54:15,897 — protonvpn-linux-gui — DEBUG — custom_quick_connect:288 — >>> Result: "CompletedProcess(args=['protonvpn', 'connect', '-f', '-p', 'udp'], returncode=1, stdout=b'', stderr=b'Traceback (m>
2020-07-03 13:54:15,897 — protonvpn-linux-gui — DEBUG — update_labels_status:387 — >>> Running "update_labels_status" getting servers, is_connected and connected_server.
2020-07-03 13:54:15,970 — protonvpn-linux-gui — DEBUG — custom_get_ip_info:1008 — Getting IP Information
2020-07-03 13:54:15,970 — protonvpn-linux-gui — DEBUG — custom_call_api:238 — Initiating custom API Call: https://api.protonvpn.ch/vpn/location
2020-07-03 13:54:16,214 — protonvpn-linux-gui — DEBUG — custom_quick_connect:292 — >>> Ended tasks in "custom_quick_connect" thread.
```
If I run the failing command `protonvpn connect -f -p udp` I get
```
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 116, in cli
    connection.fastest(protocol)
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 165, in fastest
    openvpn_connect(fastest_server, protocol)
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 450, in openvpn_connect
    shutil.copyfile(TEMPLATE_FILE, OVPN_FILE)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bnctth/.pvpn-cli/template.ovpn'
```
I had previously the newest pv cli but I had to downgrade it to this because of #83 

I hope I could help, and you can help us

**Comment by bnctth** [comment]
I have been experimenting and I found out neither reinstalling nor up/downgrading of the protonvpn-cli helps in this problem, because >=2.2.2 required for the gui, but the >=2.2.3 works neither because of #83.

**Comment by calexandru2018** [comment]
Hi @bnctt, I am not sure if your problem is exactly the same as the OP, since yours appears not even to work with the CLI.

**Comment by ghost** [comment]
Yeah, mine is working well after a fresh install, and I can't reproduce it anymore.
You may close this ticket if you prefer

**Comment by calexandru2018** [comment]
Thank you for the input @dioio-io 

I'll close this issue then :+1:
