### ISSUE TITLE
Erro run protonvpn-gui

### ISSUE THREAD

**Issue by cantalupo555** [calexandru2018/linux-gui-legacy#90]
**Describe the bug**
Installation happens normally, but when I'm going to run `protonvpn-gui` present this error.
All dependencies then installed, linux-cli too.
![](https://i.imgur.com/4tr6Sta.png)

**Screenshots**
![](https://i.imgur.com/F8wwzIk.png)

**Desktop (please complete the following information):**
 - OS: Solus Linux

**To Reproduce**
```
Traceback (most recent call last):
  File "/usr/bin/protonvpn-gui", line 11, in <module>
    load_entry_point('protonvpn-gui==2.0.7', 'console_scripts', 'protonvpn-gui')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/protonvpn_linux_gui/gui.py", line 16, in <module>
    from .utils import (
  File "/usr/lib/python3.7/site-packages/protonvpn_linux_gui/utils.py", line 12, in <module>
    from protonvpn_cli.utils import (
ImportError: cannot import name 'make_ovpn_template' from 'protonvpn_cli.utils' (/usr/lib/python3.7/site-packages/protonvpn_cli/utils.py)
```

**Comment by derekperrin** [comment]
I'm experiencing the exact same problem on Ubuntu 18.04.

**Comment by calexandru2018** [comment]
Please take a look at the previously created issues as this has already been discussed.

I'm closing this issue since it is a duplicate of #83
