### ISSUE TITLE
Error running from AUR version on Manjaro

### ISSUE THREAD

**Issue by ghost** [calexandru2018/linux-gui-legacy#92]
When running either the GUI or tray, I get the following output: 
`Traceback (most recent call last):
  File "/usr/bin/protonvpn-tray", line 11, in <module>
    load_entry_point('protonvpn-linux-gui-calexandru2018==2.0.7', 'console_scripts', 'protonvpn-tray')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/protonvpn_linux_gui/tray_icon.py", line 16, in <module>
    from .utils import get_gui_config, set_gui_config
  File "/usr/lib/python3.8/site-packages/protonvpn_linux_gui/utils.py", line 12, in <module>
    from protonvpn_cli.utils import (
ImportError: cannot import name 'make_ovpn_template' from 'protonvpn_cli.utils' (/usr/lib/python3.8/site-packages/protonvpn_cli/utils.py)`

I'm on Manjaro KDE Plasma

**Comment by calexandru2018** [comment]
Hi @PianoGuy628 , this has already been mentioned in #83
